import { CreditCardIcon } from "@phosphor-icons/react/dist/ssr";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { controlPlaneGet, roleCookie } from "@/lib/control-plane";

type Payment = { id: string; organization_name: string; event_title?: string; tier: string; participant_limit: number; amount_cents: number; currency: string; status: string; provider: string; created_at: string };

export default async function AdminPaymentsPage() {
  if ((await cookies()).get(roleCookie)?.value !== "super_admin") notFound();
  const payments = await controlPlaneGet<Payment[]>("/v1/admin/payments");
  const total = payments.filter((payment) => ["paid", "consumed"].includes(payment.status)).reduce((sum, payment) => sum + payment.amount_cents, 0);
  return <div className="space-y-8"><PageHeader eyebrow="Super amministratore" title="Pagamenti evento." description={`${payments.length} operazioni · ${(total / 100).toLocaleString("it-IT", { style: "currency", currency: "EUR" })} incassati nel registro locale.`} /><div className="overflow-x-auto rounded-[28px] border border-white/10 bg-[#111516]"><table className="w-full min-w-[860px] text-left"><thead><tr className="border-b border-white/8 font-mono text-[9px] uppercase tracking-[.15em] text-[#697170]"><th className="px-5 py-4">Pagamento</th><th className="px-5 py-4">Cliente</th><th className="px-5 py-4">Fascia</th><th className="px-5 py-4">Importo</th><th className="px-5 py-4">Stato</th><th className="px-5 py-4">Data</th></tr></thead><tbody className="divide-y divide-white/8">{payments.length === 0 && <tr><td colSpan={6} className="px-5 py-12 text-center text-xs text-[#737b79]">Nessun pagamento registrato.</td></tr>}{payments.map((payment) => <tr key={payment.id} className="hover:bg-white/[.025]"><td className="px-5 py-4"><div className="flex items-center gap-3"><CreditCardIcon size={17} className="text-[#d1e66a]" /><div><p className="font-mono text-[10px] text-white">{payment.id}</p><p className="mt-1 text-[9px] text-[#68706f]">{payment.provider}</p></div></div></td><td className="px-5 py-4"><p className="text-xs text-white">{payment.organization_name}</p><p className="mt-1 text-[10px] text-[#737b79]">{payment.event_title ?? "Non ancora usato"}</p></td><td className="px-5 py-4 text-xs text-[#aab1af]">{payment.tier} · {payment.participant_limit.toLocaleString("it-IT")}</td><td className="px-5 py-4 font-mono text-sm text-[#d1e66a]">{(payment.amount_cents / 100).toLocaleString("it-IT", { style: "currency", currency: payment.currency })}</td><td className="px-5 py-4 text-[10px] uppercase text-[#aab1af]">{payment.status}</td><td className="px-5 py-4 text-[10px] text-[#737b79]">{new Intl.DateTimeFormat("it-IT", { dateStyle: "short", timeStyle: "short" }).format(new Date(payment.created_at))}</td></tr>)}</tbody></table></div></div>;
}
