"use client";

import { GlobeHemisphereWestIcon } from "@phosphor-icons/react";
import { useEffect, useSyncExternalStore, type ReactNode } from "react";

const translations: Record<string, string> = {
  "Panoramica": "Overview",
  "Profilo": "Profile",
  "Clienti": "Customers",
  "Tutti eventi": "All events",
  "Editor guidato 2D": "Guided 2D editor",
  "Genera una base dall'alto, poi modifica liberamente settori, righe, posti, campo, palco e ingressi.": "Generate a top-down base, then freely edit sections, rows, seats, field, stage and entrances.",
  "Scegli uno strumento, tocca la pianta, personalizza e salva. Livelli, tribune, righe e singoli posti restano sempre modificabili.": "Choose a tool, touch the plan, customize and save. Levels, stands, rows and individual seats always remain editable.",
  "Parti da una base automatica e segui i quattro passi. Puoi aggiungere livelli, tribune, palchi, righe e posti oppure importare il lotto dalla mappa.": "Start from an automatic base and follow the four steps. Add levels, stands, stages, rows and seats, or import the parcel from the map.",
  "Crea la coreografia, un effetto alla volta.": "Create the choreography, one effect at a time.",
  "Scegli settori, colore e durata oppure importa un'immagine o un video. Pubblica la timeline quando l'anteprima è pronta.": "Choose sections, color and duration, or import an image or video. Publish the timeline when the preview is ready.",
  "Crea effetto": "Create effect",
  "Pubblica timeline": "Publish timeline",
  "Pubblicazione…": "Publishing…",
  "Timeline pubblicata ✓": "Timeline published ✓",
  "Riprova pubblicazione": "Retry publishing",
  "Crea un effetto": "Create an effect",
  "Importa un media": "Import media",
  "Crea il primo effetto oppure importa un'immagine o un video.": "Create the first effect or import an image or video.",
  "Aggiungi effetto alla timeline": "Add effect to timeline",
  "Scegli immagine o video": "Choose image or video",
  "Scegli un'immagine, una GIF o un video: verrà trasformato automaticamente in effetti sincronizzati.": "Choose an image, GIF or video: it will automatically become synchronized effects.",
  "Modifiche salvate": "Changes saved",
  "Salva modifiche": "Save changes",
  "Annulla ultima modifica": "Undo last change",
  "Ripeti modifica": "Redo change",
  "1 · Scegli uno strumento": "1 · Choose a tool",
  "2 · Tocca la pianta": "2 · Touch the plan",
  "3 · Personalizza a destra": "3 · Customize on the right",
  "4 · Salva le modifiche": "4 · Save changes",
  "Seleziona e modifica": "Select and edit",
  "Disegna un'area": "Draw an area",
  "Aggiungi un posto": "Add a seat",
  "Importa da mappa": "Import from map",
  "Mostra altri elementi": "Show more elements",
  "Nascondi elementi avanzati": "Hide advanced elements",
  "Rigenera tutta la pianta": "Regenerate entire plan",
  "Azione avanzata: sostituisce gli elementi attuali dopo una conferma.": "Advanced action: replaces current elements after confirmation.",
  "VERSIONE DELLA PIANTA": "PLAN VERSION",
  "Crea varianti senza perdere l'originale.": "Create variants without losing the original.",
  "MODIFICA ELEMENTO": "EDIT ELEMENT",
  "Rotazione (gradi)": "Rotation (degrees)",
  "Numero di righe": "Number of rows",
  "Posti per riga": "Seats per row",
  "Forma delle righe": "Row shape",
  "Dritte": "Straight",
  "Curve": "Curved",
  "posti personalizzati": "customized seats",
  "Aggiungi sulla pianta": "Add on plan",
  "Blocca posizione": "Lock position",
  "Elimina elemento": "Delete element",
  "Clicca un elemento sulla pianta. Qui compariranno nome, dimensioni, righe, posti e rotazione.": "Click an element on the plan. Its name, size, rows, seats and rotation will appear here.",
  "Modifica effetti": "Edit effects",
  "1 · Configura": "1 · Configure",
  "2 · Aggiungi": "2 · Add",
  "3 · Pubblica": "3 · Publish",
  "Seleziona un elemento sulla pianta per spostarlo o modificarlo.": "Select an element on the plan to move or edit it.",
  "Disegna un'area: clicca almeno 3 punti sulla pianta, poi premi Completa.": "Draw an area: click at least 3 points on the plan, then press Complete.",
  "Prima seleziona un settore con posti, poi usa questo strumento.": "First select a section with seats, then use this tool.",
  "Crea una copia della configurazione": "Create a copy of the configuration",
  "Crea una copia": "Create a copy",
  "Predefinita": "Default",
  "Imposta predefinita": "Set as default",
  "Archivia configurazione": "Archive configuration",
  "Archiviate": "Archived",
  "Ripristina": "Restore",
  "Questa configurazione verrà proposta per prima nei nuovi eventi.": "This configuration will be selected first for new events.",
  "Configurazione archiviata. Non verrà proposta nei nuovi eventi.": "Configuration archived. It will not be offered for new events.",
  "Configurazione ripristinata e nuovamente disponibile.": "Configuration restored and available again.",
  "Strutture": "Venues",
  "Eventi": "Events",
  "Accesso": "Access",
  "Esperienza": "Experience",
  "Conferma": "Review",
  "Report": "Reports",
  "Profilo e brand": "Profile & brand",
  "Organizzazioni": "Organizations",
  "Utenti": "Users",
  "Pagamenti": "Payments",
  "Tutti gli eventi": "All events",
  "Organizzazione": "Organization",
  "Navigazione principale": "Main navigation",
  "Esci dalla regia": "Sign out of control",
  "Super amministratore": "Super administrator",
  "Nuova organizzazione": "New organization",
  "Licenza": "License",
  "Dispositivi": "Devices",
  "Sospesa": "Suspended",
  "Solo il super amministratore può creare credenziali, modificare licenze o sospendere un cliente.": "Only the super administrator can create credentials, edit licenses or suspend a customer.",
  "Amministratore organizzazione": "Organization administrator",
  "organization_admin": "Organization administrator",
  "super_admin": "Super administrator",
  "Sessione autenticata": "Authenticated session",
  "Accesso organizzazioni": "Organization sign-in",
  "La regia comincia qui.": "Control starts here.",
  "Accedi come organizzatore. Se è la prima volta, crea il tuo account e sblocca gratuitamente un evento demo.": "Sign in as an organizer. If this is your first time, create an account and unlock a demo event for free.",
  "Usa le credenziali assegnate dall'amministratore onePixel. I partecipanti non devono accedere: per loro basta il QR.": "Use the credentials assigned by the onePixel administrator. Participants do not need to sign in: their QR is enough.",
  "onePixel control surface · accesso protetto": "onePixel control surface · protected access",
  "Una folla, un solo istante.": "One crowd, one moment.",
  "Stadio illuminato da una coreografia onePixel": "Stadium illuminated by a onePixel choreography",
  "Mappa dello stadio vista dall'alto con quattro settori": "Top-down stadium map with four sections",
  "Email organizzazione": "Organization email",
  "La sessione resta protetta da cookie HttpOnly.": "Your session is protected by an HttpOnly cookie.",
  "Non hai un account?": "Don't have an account?",
  "Registrati": "Register",
  "Contatta onePixel se le credenziali sono scadute.": "Contact onePixel if your credentials have expired.",
  "Accesso in corso…": "Signing in…",
  "Accedi alla regia": "Open control room",
  "Accesso non riuscito": "Sign-in failed",
  "DAL PAGAMENTO ALLA REGIA": "FROM PAYMENT TO CONTROL",
  "DALLO SBLOCCO DEMO ALLA REGIA": "FROM DEMO UNLOCK TO CONTROL",
  "Costruisci l'evento. Accendi ogni schermo.": "Build the event. Light every screen.",
  "Il primo evento piccolo, senza abbonamento.": "Your first small event, with no subscription.",
  "partecipanti inclusi": "participants included",
  "NUOVO ORGANIZZATORE": "NEW ORGANIZER",
  "Apri la tua regia.": "Open your control room.",
  "Registrati, scegli la capienza e paga un solo evento. La procedura guidata parte immediatamente.": "Register, choose capacity and pay for one event. The guided setup starts immediately.",
  "Registrati, scegli la capienza e sblocca un evento mock senza addebiti. La procedura guidata parte immediatamente.": "Register, choose capacity and unlock a mock event with no charge. Guided setup starts immediately.",
  "Il tuo nome": "Your name",
  "Almeno 10 caratteri. Non chiediamo abbonamenti.": "At least 10 characters. No subscription required.",
  "Creazione account…": "Creating account…",
  "Crea account e scegli evento": "Create account and choose event",
  "Hai già un account?": "Already have an account?",
  "Accedi": "Sign in",
  "Registrazione non riuscita": "Registration failed",
  "Centro di controllo": "Control center",
  "Nessun evento": "No events",
  "Crea il primo evento": "Create your first event",
  "CENTRO DI CONTROLLO": "CONTROL CENTER",
  "Prepara, verifica, poi vai in scena.": "Prepare, verify, then go live.",
  "Qui trovi lo stato reale di strutture, pacchetti e dispositivi. Ogni avviso indica la prossima azione da completare prima della diretta.": "See the actual state of venues, packages and devices. Every alert shows the next action to complete before going live.",
  "Crea evento": "Create event",
  "EVENTO IN EVIDENZA": "FEATURED EVENT",
  "Evento in evidenza": "Featured event",
  "Stato operativo": "Operational status",
  "In preparazione": "In preparation",
  "Dispositivi collegati": "Connected devices",
  "Struttura assegnata": "Venue assigned",
  "Pianta da controllare": "Plan needs review",
  "Pacchetto pubblicato": "Package published",
  "Apri lo studio e pubblica": "Open the studio and publish",
  "Dispositivi pronti": "Devices ready",
  "Nessun dispositivo collegato": "No devices connected",
  "Pacchetto pronto": "Package ready",
  "Offset medio": "Average offset",
  "Continua configurazione": "Continue setup",
  "Apri prova e regia": "Open rehearsal and control",
  "Entra nella regia live": "Enter live control",
  "Apri il report": "Open report",
  "Bozza": "Draft",
  "Pubblicato": "Published",
  "In diretta": "Live",
  "Arrestato": "Stopped",
  "Concluso": "Completed",
  "Nessun evento configurato": "No event configured",
  "Crea una struttura, sblocca un evento e completa il percorso guidato. La panoramica mostrerà solo dati realmente disponibili.": "Create a venue, unlock an event and finish the guided setup. The overview only shows data that is actually available.",
  "Inizia configurazione": "Start setup",
  "Eventi e prossime azioni": "Events and next actions",
  "Vedi tutti": "View all",
  "Percorso di preparazione": "Preparation path",
  "Apri direttamente l'area che devi completare. Nessuno stato viene dato per pronto senza dati.": "Open the area you need to complete. Nothing is marked ready without data.",
  "Strutture e configurazioni": "Venues and configurations",
  "Eventi, effetti e regia": "Events, effects and control",
  "Report e risultati": "Reports and results",
  "Profilo e identità": "Profile and identity",
  "I dati realtime compaiono solo quando un evento è pubblicato o live.": "Realtime data appears only when an event is published or live.",
  "Nessuna organizzazione selezionata": "No organization selected",
  "Il profilo globale onePixel non ha un brand organizzazione. Apri la gestione clienti per configurare o controllare le organizzazioni abilitate.": "The global onePixel profile has no organization brand. Open customer management to configure or review enabled organizations.",
  "Gestisci organizzazioni": "Manage organizations",
  "Nessun utente registrato.": "No registered users.",
  "Nessun evento presente nella piattaforma.": "No events in the platform.",
  "Nessuna organizzazione creata. Usa il pulsante in alto per aggiungere il primo cliente.": "No organizations created. Use the button above to add the first customer.",
  "Nessun pagamento registrato.": "No payments recorded.",
  "Sblocca un evento": "Unlock an event",
  "Scegli soltanto la capienza che ti serve.": "Choose only the capacity you need.",
  "Il pagamento è simulato: nessuna carta e nessun addebito. Passi subito alla configurazione guidata e puoi provare anche l’upgrade.": "Payment is simulated: no card and no charge. You move straight to guided setup and can also test upgrades.",
  "Paghi una volta e passi subito alla configurazione guidata. Se durante l'evento serve più capienza, potrai effettuare l'upgrade.": "Pay once and move straight to guided setup. If you need more capacity during the event, you can upgrade.",
  "Evento piccolo": "Small event",
  "Evento medio": "Medium event",
  "Evento grande": "Large event",
  "Un pagamento, un evento.": "One payment, one event.",
  "Sblocco demo, nessun addebito.": "Demo unlock, no charge.",
  "Editor completo della struttura": "Complete venue editor",
  "QR, GPS e regia sincronizzata": "QR, GPS and synchronized control",
  "Nessun rinnovo automatico": "No automatic renewal",
  "Nessuna carta e nessun addebito": "No card and no charge",
  "Sblocca evento demo": "Unlock demo event",
  "Attivazione demo…": "Activating demo…",
  "MODALITÀ MOCK · NESSUN ADDEBITO": "MOCK MODE · NO CHARGE",
  "Continua al pagamento": "Continue to payment",
  "Apertura pagamento…": "Opening payment…",
  "PAGAMENTO SICURO STRIPE": "SECURE STRIPE PAYMENT",
  "Pagamento demo completato": "Demo payment completed",
  "Hai sbloccato un evento fino a": "You unlocked one event for up to",
  "partecipanti. Ora puoi configurarlo.": "participants. You can now configure it.",
  "Configura evento": "Configure event",
  "Programma. Prova. Trasmetti.": "Plan. Rehearse. Broadcast.",
  "Ogni evento contiene assegnazione QR, media, timeline e regia live in un unico flusso controllato.": "Every event includes QR assignment, media, timeline and live control in one managed flow.",
  "Ogni posto ha coordinate precise.": "Every seat has precise coordinates.",
  "Genera una base dall'alto, poi modifica liberamente settori, file, posti, campo, palco e ingressi.": "Generate a top-down base, then freely edit sections, rows, seats, field, stage and entrances.",
  "Nuova struttura": "New venue",
  "Fiera": "Fairground",
  "Manifestazione": "Demonstration",
  "Aggregazione": "Gathering",
  "Corteo": "March",
  "Evento civico": "Civic event",
  "Evento temporaneo": "Temporary event",
  "Altro": "Other",
  "Personalizzata": "Custom",
  "Tavola 2D della struttura": "2D venue canvas",
  "Piano terra": "Ground floor",
  "Nome configurazione": "Configuration name",
  "Configurazione principale": "Main configuration",
  "Duplica configurazione": "Duplicate configuration",
  "Aggiungi livello": "Add level",
  "Mostra livello": "Show level",
  "Nascondi livello": "Hide level",
  "Blocca livello": "Lock level",
  "Elimina livello": "Delete level",
  "Editor universale 2D": "Universal 2D editor",
  "Costruisci qualsiasi spazio dall'alto.": "Build any space from above.",
  "Parti da uno stadio, un palazzetto, un concerto o un'area libera. Aggiungi livelli, tribune, palchi, file e posti, oppure importa il lotto dalla mappa.": "Start from a stadium, arena, concert or open area. Add levels, stands, stages, rows and seats, or import the parcel from the map.",
  "PASSO 01 · BASE AUTOMATICA": "STEP 01 · AUTOMATIC BASE",
  "Passo 01 · Base automatica": "Step 01 · Automatic base",
  "Che spazio vuoi costruire?": "What space do you want to build?",
  "onePixel genera una pianta dall'alto proporzionata alla capienza. Dopo questo passo ogni vertice, fila, posto e livello rimane modificabile.": "onePixel generates a top-down plan sized to capacity. After this step every vertex, row, seat and level remains editable.",
  "Stadio": "Stadium",
  "Anelli, campo e settori": "Rings, field and sections",
  "Palazzetto": "Indoor arena",
  "Compatto e multilivello": "Compact and multilevel",
  "Concerto": "Concert",
  "Palco e platea": "Stage and audience floor",
  "Piazza": "Public square",
  "Manifestazioni e raduni": "Demonstrations and gatherings",
  "Area esterna": "Outdoor area",
  "Cortei e spazi liberi": "Marches and open spaces",
  "Da zero": "From scratch",
  "Tavola completamente libera": "Completely free canvas",
  "DIMENSIONAMENTO": "SIZING",
  "Dimensionamento": "Sizing",
  "Nome struttura": "Venue name",
  "Quanti posti?": "How many seats?",
  "Livelli / anelli": "Levels / rings",
  "posti distribuiti automaticamente su 2 livelli": "seats automatically distributed across 2 levels",
  "posti distribuiti automaticamente su": "seats automatically distributed across",
  "livelli": "levels",
  "Genera la pianta": "Generate plan",
  "Livelli, tribune, curve, palchi, file e singoli posti: ogni configurazione resta versionata e modificabile.": "Levels, stands, curves, stages, rows and individual seats: every configuration remains versioned and editable.",
  "Anello inferiore": "Lower ring",
  "Anello intermedio": "Middle ring",
  "Anello superiore": "Upper ring",
  "Campo centrale": "Main field",
  "Palco modulare nord": "North modular stage",
  "Pedana accessibile": "Accessible platform",
  "Campionato + palco": "Match + stage",
  "Configurazione guidata": "Guided setup",
  "Crea il tuo evento, senza saltare nulla.": "Create your event without missing anything.",
  "Struttura, posizione, QR o GPS, capofila mobile e permessi della regia: il wizard prepara tutto prima dello studio.": "Venue, location, QR or GPS, mobile leader and control permissions: the wizard prepares everything before the studio.",
  "IDENTITÀ E STRUTTURA": "IDENTITY & VENUE",
  "Diamo forma all'evento.": "Let's shape the event.",
  "Nome evento": "Event name",
  "Tipo": "Type",
  "Struttura": "Venue",
  "Configurazione": "Configuration",
  "Descrizione": "Description",
  "Racconta cosa vedranno i partecipanti…": "Describe what participants will see…",
  "Fascia sbloccata": "Unlocked tier",
  "partecipanti massimi": "maximum participants",
  "CONFIGURAZIONE SCELTA": "SELECTED CONFIGURATION",
  "POSIZIONE E INGRESSO": "LOCATION & ENTRY",
  "Come entrano le persone?": "How do people join?",
  "Luogo": "Location",
  "Stadio, piazza o punto di ritrovo": "Stadium, square or meeting point",
  "Inizio": "Start",
  "Durata": "Duration",
  "Metodi validi": "Valid methods",
  "Autorità esatta per settore e posto": "Exact authority for section and seat",
  "Area GPS fissa": "Fixed GPS area",
  "Aggancio automatico nella macro-area": "Automatic join in the macro area",
  "Raggio mobile": "Mobile radius",
  "Segue il telefono admin, ideale per cortei": "Follows the admin phone, ideal for marches",
  "Usa il confine catastale selezionato": "Use the selected cadastral boundary",
  "Aggiungi tappa qui": "Add stop here",
  "tappe nel percorso facoltativo": "stops in the optional route",
  "Azzera": "Clear",
  "ESPERIENZA PARTECIPANTE": "PARTICIPANT EXPERIENCE",
  "Decidi cosa può attivare la regia.": "Choose what control may activate.",
  "Audio e cori": "Audio & chants",
  "La regia può proporli; ogni utente conserva la scelta finale.": "Control may offer them; each user keeps the final choice.",
  "Torcia e luce": "Torch & light",
  "Coreografie luminose sincronizzate, con consenso dell'utente.": "Synchronized light choreographies, with user consent.",
  "Visibilità": "Visibility",
  "Pubblico · visibile nelle vicinanze": "Public · visible nearby",
  "Privato · accesso tramite metodi scelti": "Private · access through selected methods",
  "Copertina evento · carica file": "Event cover · upload file",
  "Oppure usa un URL immagine": "Or use an image URL",
  "Programma · una voce per riga": "Schedule · one item per line",
  "Apertura cancelli\nInizio spettacolo\nCoreografia finale": "Doors open\nShow starts\nFinal choreography",
  "Usa la posizione attuale": "Use current location",
  "CONSENTITO": "ALLOWED",
  "DISATTIVATO": "DISABLED",
  "Apertura cancelli": "Doors open",
  "Inizio spettacolo": "Show starts",
  "Coreografia finale": "Final choreography",
  "RIEPILOGO": "SUMMARY",
  "Pronto per entrare in regia.": "Ready to enter control.",
  "Evento": "Event",
  "Ingresso": "Entry",
  "Pubblico": "Audience",
  "Controlli": "Controls",
  "Dopo la creazione apriremo lo studio: potrai caricare media, generare QR e costruire la timeline prima di pubblicare.": "After creation we will open the studio: upload media, generate QR and build the timeline before publishing.",
  "Indietro": "Back",
  "Continua": "Continue",
  "Creazione…": "Creating…",
  "Crea e apri lo studio": "Create and open studio",
  "Disegna il momento, fotogramma per fotogramma.": "Design the moment, frame by frame.",
  "Colora i posti, importa immagini o video e orchestra audio, testo, vibrazione e flash su una timeline unica.": "Color seats, import images or video and orchestrate audio, text, vibration and flash on one timeline.",
  "Apri regia live": "Open live control",
  "Aumenta capienza": "Increase capacity",
  "Aumenta la capienza dell’evento.": "Increase event capacity.",
  "Limite attuale:": "Current limit:",
  "partecipanti. Il nuovo pagamento viene collegato soltanto a questo evento.": "participants. The new payment is linked only to this event.",
  "Applico la nuova fascia.": "Applying the new tier.",
  "Il pagamento è confermato; aggiorniamo il limite senza interrompere chi è già collegato.": "Payment is confirmed; we are updating the limit without interrupting connected participants.",
  "Lo sblocco demo è confermato; aggiorniamo il limite senza interrompere chi è già collegato.": "The demo unlock is confirmed; we are updating the limit without interrupting connected participants.",
  "Verifico il pagamento e aggiorno la capienza…": "Verifying payment and updating capacity…",
  "Verifico lo sblocco mock e aggiorno la capienza…": "Verifying the mock unlock and updating capacity…",
  "Upgrade non applicato": "Upgrade not applied",
  "Serve un controllo": "A check is required",
  "Upgrade evento": "Event upgrade",
  "Assegnazione accesso": "Access assignment",
  "Genera QR firmati": "Generate signed QR codes",
  "Il QR prevale sul GPS e può assegnare una zona o un singolo posto. L'app funziona anche senza account.": "QR overrides GPS and can assign a zone or an individual seat. The app works without an account.",
  "QR zona": "Zone QR",
  "QR posto": "Seat QR",
  "Zona": "Zone",
  "Fila-posto": "Row-seat",
  "Firma in corso…": "Signing…",
  "Genera QR": "Generate QR",
  "Scarica PNG": "Download PNG",
  "Il codice comparirà qui": "The code will appear here",
  "Esportazione massiva": "Bulk export",
  "Tutte le zone oppure ogni posto della configurazione congelata nell'evento.": "Every zone or every seat in the configuration frozen for the event.",
  "Genera per zone": "Generate by zone",
  "Genera per posti": "Generate by seat",
  "Preparazione lotto…": "Preparing batch…",
  "codici pronti": "codes ready",
  "Disegna": "Draw",
  "Importa media": "Import media",
  "Colori": "Colors",
  "Audio": "Audio",
  "Testo": "Text",
  "Vibrazione": "Vibration",
  "Riproduci anteprima": "Play preview",
  "Metti in pausa": "Pause preview",
  "Durata massima": "Maximum duration",
  "Importa": "Import",
  "Pubblica": "Publish",
  "Pubblicata ✓": "Published ✓",
  "Riprova": "Retry",
  "Componi un cue": "Compose a cue",
  "Aggiungi il primo cue manuale o importa un media.": "Add the first manual cue or import media.",
  "Importa PNG, JPG, GIF o video": "Import PNG, JPG, GIF or video",
  "Media convertito": "Converted media",
  "Settori destinatari": "Target sections",
  "Colore schermi": "Screen color",
  "Testo italiano": "Italian text",
  "Testo inglese": "English text",
  "Durata s": "Duration s",
  "Carica coro o traccia audio": "Upload chant or audio track",
  "Nessun audio": "No audio",
  "Flash": "Flash",
  "Aggiungi cue alla timeline": "Add cue to timeline",
  "cue pronti": "cues ready",
  "Scegli media": "Choose media",
  "Un gesto. Migliaia di schermi.": "One gesture. Thousands of screens.",
  "Controlla copertura e sincronizzazione prima di armare la regia. Ogni comando critico resta visibile e registrato.": "Check coverage and synchronization before arming control. Every critical command remains visible and logged.",
  "Sincronizzazione": "Synchronization",
  "connessioni realtime": "realtime connections",
  "offset medio assoluto": "average absolute offset",
  "CAPOFILA MOBILE": "MOBILE LEADER",
  "Questo telefono è l'aggancio": "This phone is the anchor",
  "Chi entra nel raggio resta associato anche quando si allontana. Se la rete cade, rimane valida l'ultima posizione.": "Anyone joining within the radius remains attached after moving away. If the network drops, the last position remains valid.",
  "Ferma capofila": "Stop leader",
  "Avvia capofila": "Start leader",
  "Regia live": "Live control",
  "Ultimo comando": "Last command",
  "Nessun comando inviato": "No command sent",
  "Arma la regia": "Arm control",
  "Avvia trasmissione": "Start broadcast",
  "Trasmissione attiva": "Broadcast active",
  "Comandi immediati": "Immediate commands",
  "Vibra": "Vibrate",
  "Colore": "Color",
  "Arresto generale": "Emergency stop",
  "Misura ciò che è successo davvero.": "Measure what actually happened.",
  "Copertura, precisione temporale, pacchetti scaricati e problemi di rete restano disponibili dopo ogni evento.": "Coverage, timing precision, downloaded packages and network issues remain available after every event.",
  "dispositivi unici rilevati": "unique devices detected",
  "Copertura media": "Average coverage",
  "scarto assoluto registrato": "recorded absolute deviation",
  "Comandi live": "Live commands",
  "Copertura per settore": "Coverage by section",
  "Segnali operativi": "Operational signals",
  "Esporta CSV": "Export CSV",
  "Nessun dato": "No data",
  "I dati compariranno dopo i primi collegamenti.": "Data will appear after the first connections.",
  "Profilo organizzazione": "Organization profile",
  "La tua identità, dentro ogni evento.": "Your identity, inside every event.",
  "Nome, colore e logo vengono distribuiti nell'app insieme al pacchetto della coreografia.": "Name, color and logo are delivered in the app with the choreography package.",
  "Nome, colore e logo vengono distribuiti nell’app insieme al pacchetto della coreografia.": "Name, color and logo are delivered in the app with the choreography package.",
  "IDENTITÀ ORGANIZZAZIONE": "ORGANIZATION IDENTITY",
  "Nome pubblico": "Public name",
  "Colore principale": "Primary color",
  "Salvataggio…": "Saving…",
  "Salva identità": "Save identity",
  "Salvataggio non riuscito.": "Save failed.",
  "ANTEPRIMA NELL'APP": "PREVIEW IN APP",
  "Identità applicata a manifest, eventi e regia": "Identity applied to manifests, events and control",
  "Salvato": "Saved",
  "Seleziona": "Select",
  "Forma libera": "Free shape",
  "Posto manuale": "Manual seat",
  "Mappa e catasto": "Map & cadastre",
  "AGGIUNGI ELEMENTO": "ADD ELEMENT",
  "Settore": "Section",
  "Tribuna": "Stand",
  "Curva": "Curve",
  "Blocco posti": "Seat block",
  "Palco": "Stage",
  "Passerella": "Runway",
  "Campo": "Field",
  "Area in piedi": "Standing area",
  "Area accessibile": "Accessible area",
  "Area tecnica": "Technical area",
  "Uscita": "Exit",
  "Corridoio": "Aisle",
  "Transenna": "Barrier",
  "Area libera": "Free area",
  "Tipo struttura": "Venue type",
  "Rigenera base": "Regenerate base",
  "CONFIGURAZIONE": "CONFIGURATION",
  "LIVELLI": "LEVELS",
  "PROPRIETÀ": "PROPERTIES",
  "Nome": "Name",
  "Larghezza": "Width",
  "Altezza": "Height",
  "Rotazione": "Rotation",
  "File": "Rows",
  "Posti / fila": "Seats / row",
  "Andamento": "Layout",
  "Dritto": "Straight",
  "Curvo": "Curved",
  "Singoli posti": "Individual seats",
  "override configurati": "configured overrides",
  "Posiziona": "Place",
  "Fila": "Row",
  "Posto": "Seat",
  "Accessibile": "Accessible",
  "Escludi": "Exclude",
  "Blocca": "Lock",
  "Sblocca": "Unlock",
  "Elimina": "Delete",
  "Seleziona un elemento per modificarne dimensioni, file, posti e rotazione.": "Select an element to edit dimensions, rows, seats and rotation.",
  "Clicca i vertici, poi completa": "Click the vertices, then complete",
  "Completa": "Complete",
  "MAPPA E CATASTO": "MAP & CADASTRE",
  "Collega il confine reale": "Link the real boundary",
  "Il dato ufficiale resta tra le fonti; nell'editor puoi spostare e modificare ogni vertice della copia 2D.": "The official data remains a source; in the editor you may move and edit every vertex of the 2D copy.",
  "Aggiungi al lotto": "Add to parcel",
  "Sostituisci confine": "Replace boundary",
  "Usa nell'editor": "Use in editor",
  "Clicca sulla mappa per scegliere il punto e cercare la particella.": "Click the map to select a point and search for the parcel.",
  "Ricerca del confine catastale…": "Searching cadastral boundary…",
  "Posizione non disponibile. Seleziona manualmente sulla mappa.": "Location unavailable. Select it manually on the map.",
  "Controllo globale eventi.": "Global event control.",
  "Sorveglia stato, organizzazione, capienza e partecipanti; puoi arrestare un evento senza entrare nella sua regia.": "Monitor status, organization, capacity and participants; stop an event without entering its control room.",
  "Pagamenti evento.": "Event payments.",
  "Utenti e accessi.": "Users & access.",
  "Un'unica vista su amministratori onePixel e account delle organizzazioni.": "One view of onePixel administrators and organization accounts.",
  "Un’unica vista su amministratori onePixel e account delle organizzazioni.": "One view of onePixel administrators and organization accounts.",
  "Decidi chi può accendere la piattaforma.": "Decide who may activate the platform.",
  "Crea le organizzazioni dopo la vendita, assegna credenziali e limiti e conserva il controllo operativo generale.": "Create organizations after the sale, assign credentials and limits, and retain overall operational control.",
  "Password iniziale": "Initial password",
  "Nome organizzazione": "Organization name",
  "Email amministratore": "Administrator email",
  "Limiti licenza": "License limits",
  "Pagamento": "Payment",
  "Cliente": "Customer",
  "Fascia": "Tier",
  "Importo": "Amount",
  "Stato": "Status",
  "small": "Small",
  "medium": "Medium",
  "large": "Large",
  "paid": "Paid",
  "consumed": "Consumed",
  "pending": "Pending",
  "failed": "Failed",
  "Bozza": "Draft",
  "Pubblicato": "Published",
  "Fermato": "Stopped",
  "sport": "Sport",
  "Data": "Date",
  "operazioni": "transactions",
  "incassati nel registro locale.": "received in the local ledger.",
  "Non ancora usato": "Not used yet",
  "Utente": "User",
  "Ruolo": "Role",
  "Ultimo accesso": "Last sign-in",
  "Senza nome": "No name",
  "Attivo": "Active",
  "Disabilitato": "Disabled",
  "Mai": "Never",
  "fino al": "until",
  "capienza": "capacity",
  "Partecipanti": "Participants",
  "Fino a": "Up to",
  "partecipanti, un solo evento.": "participants, one event.",
  "posti": "seats",
  "settori configurati": "configured sections",
  "pronti su": "ready out of",
  "offset medio": "average offset",
  "PRONTO": "READY",
  "Quando": "When",
  "Nuovo cliente B2B": "New B2B customer",
  "Crea accesso e licenza": "Create access & license",
  "Ragione sociale": "Business name",
  "Scadenza licenza": "License expiry",
  "Colore brand": "Brand color",
  "Eventi massimi": "Maximum events",
  "Dispositivi massimi": "Maximum devices",
  "Capienza massima struttura": "Maximum venue capacity",
  "Crea organizzazione e credenziali": "Create organization and credentials",
  "Chiudi": "Close",
  "Mostra password": "Show password",
  "Nascondi password": "Hide password",
  "Annulla": "Undo",
  "Ripeti": "Redo",
  "Salva": "Save",
  "Privato": "Private",
  "ore": "hours",
  "PERCORSO DEL CORTEO": "MARCH ROUTE",
  "Traccia il tragitto sulla mappa": "Trace the route on the map",
  "Come si usa:": "How it works:",
  "ogni clic aggiunge una tappa e collega automaticamente il percorso.": "each click adds a stop and automatically connects the route.",
  "Annulla ultimo punto": "Undo last point",
  "Cancella percorso": "Clear route",
  "Aggiungi la prima tappa": "Add the first stop",
  "Clicca sulla mappa. Potrai decidere cosa compare e se attivarlo manualmente, a un orario o all’arrivo.": "Click the map. You can choose what appears and whether it starts manually, on schedule, or on arrival.",
  "MODIFICA TAPPA": "EDIT STOP",
  "Nome facile da riconoscere": "Easy-to-recognize name",
  "Quando parte l’effetto": "When the effect starts",
  "Manuale · decido io dalla regia": "Manual · I decide from live control",
  "Programmato · dopo l’avvio": "Scheduled · after the start",
  "Automatico · quando arriva il capofila": "Automatic · when the leader arrives",
  "Minuti dopo l’avvio": "Minutes after the start",
  "Testo che compare": "Text shown on screen",
  "Colore degli schermi": "Screen color",
  "Questa tappa è attiva": "This stop is active",
  "Salva percorso e tappe": "Save route and stops",
  "Percorso salvato": "Route saved",
  "Traccia il percorso del corteo": "Trace the march route",
  "Clicca nell’ordine: partenza, tappe e arrivo. Potrai configurare gli effetti nello studio.": "Click in order: start, stops, and finish. You can configure effects in the studio.",
  "CORTEO IN TEMPO REALE": "LIVE MARCH",
  "Percorso e posizione del capofila": "Route and leader position",
  "TAPPE ED EFFETTI": "STOPS AND EFFECTS",
  "Gestisci cosa appare lungo il percorso": "Manage what appears along the route",
  "Puoi lanciare subito, mettere in pausa una tappa o riarmarla senza fermare il corteo.": "Launch immediately, pause a stop, or re-arm it without stopping the march.",
  "Riattiva tutte": "Re-arm all",
  "Modifica percorso": "Edit route",
  "Programmato e inviato ai dispositivi": "Scheduled and sent to devices",
  "Effetto già eseguito": "Effect already run",
  "Manuale": "Manual",
  "Attiva": "Active",
  "In pausa": "Paused",
  "Avvia effetto adesso": "Run effect now",
  "Capofila": "Leader",
};

const replacements: Array<[RegExp, string]> = [
  [/^Modifica (.+)\.$/g, "Edit $1."],
  [/^(.+) · Editor effetti$/g, "$1 · Effects editor"],
  [/^Stai modificando Settore (.+)\. Trascinalo sulla pianta o usa le proprietà a destra\.$/g, "You are editing Section $1. Drag it on the plan or use the properties on the right."],
  [/^Stai modificando (.+)\. Trascinalo sulla pianta o usa le proprietà a destra\.$/g, "You are editing $1. Drag it on the plan or use the properties on the right."],
  [/^Aggiungi posti a Settore (.+): clicca sulla pianta nel punto desiderato\.$/g, "Add seats to Section $1: click the desired point on the plan."],
  [/^Aggiungi posti a (.+): clicca sulla pianta nel punto desiderato\.$/g, "Add seats to $1: click the desired point on the plan."],
  [/^(\d+) effetti creati a mano$/g, "$1 manually created effects"],
  [/^(\d+) effetti generati dal media$/g, "$1 effects generated from media"],
  [/^Effetto aggiunto a (.+) per (.+)\.$/g, "Effect added at $1 for $2."],
  [/^(\d+) effetti pubblicati e disponibili anche offline\.$/g, "$1 effects published and available offline."],
  [/^(\d+) effetti pronti$/g, "$1 effects ready"],
  [/^(\d+) tappe salvate\. La regia live è pronta per gestirle\.$/g, "$1 stops saved. Live control is ready to manage them."],
  [/^(\d+) di (\d+) tappe eseguite$/g, "$1 of $2 stops completed"],
  [/^Punto (\d+) di (\d+)$/g, "Point $1 of $2"],
  [/^Automatico entro (\d+) m$/g, "Automatic within $1 m"],
  [/^Al minuto (\d+)$/g, "At minute $1"],
  [/^1 livello$/g, "1 level"],
  [/^(\d+) livelli$/g, "$1 levels"],
  [/\b1 LEVELS\b/g, "1 LEVEL"],
  [/\bPOSTI ·/g, "SEATS ·"],
  [/\bLIVELLI ·/g, "LEVELS ·"],
  [/^Settore ([A-Z0-9.-]+)$/g, "Section $1"],
  [/\b1 LEVELS\b/g, "1 LEVEL"],
  [/^Ingresso ([A-Z0-9.-]+)$/g, "Entrance $1"],
  [/Configurazione principale/g, "Main configuration"],
  [/GPS fisso/g, "fixed GPS"],
  [/\btorcia\b/g, "torch"],
  [/^Seleziona colore (.+)$/g, "Select color $1"],
  [/^Sospendi (.+)$/g, "Suspend $1"],
  [/^Riattiva (.+)$/g, "Reactivate $1"],
  [/Sequenza live avviata/g, "Live sequence started"],
  [/Arresto generale inviato/g, "Emergency stop sent"],
  [/sequenza (\d+)/g, "sequence $1"],
  [/(\d+) device live/g, "$1 live devices"],
  [/\b1 emergency stops\b/g, "1 emergency stop"],
  [/\b1 transactions\b/g, "1 transaction"],
  [/(\d[\d.]*) POSTI · (\d+) LIVELLI/g, "$1 SEATS · $2 LEVELS"],
  [/(\d[\d.]*) DISPOSITIVI/g, "$1 DEVICES"],
  [/Fino a ([\d.]+) partecipanti/g, "Up to $1 participants"],
  [/fino a ([\d.]+) partecipanti/g, "up to $1 participants"],
  [/un solo evento\./g, "one event."],
  [/Durata massima ([\d:]+)/g, "Maximum duration $1"],
  [/(\d+) ore/g, "$1 hours"],
  [/(\d+) codici pronti/g, "$1 codes ready"],
  [/(\d+) override configurati/g, "$1 configured overrides"],
  [/(\d+) settori configurati/g, "$1 configured sections"],
  [/(\d+) settori misurati/g, "$1 measured sections"],
  [/(\d+) settori/g, "$1 sections"],
  [/(\d+) connessioni realtime/g, "$1 realtime connections"],
  [/(\d+) dispositivi pronti/g, "$1 devices ready"],
  [/(\d+) arresti generali/g, "$1 emergency stops"],
  [/(\d+) pronti su (\d+)/g, "$1 ready out of $2"],
  [/offset medio ([\d.]+) ms/g, "average offset $1 ms"],
  [/operazioni/g, "transactions"],
  [/incassati nel registro locale/g, "received in the local ledger"],
  [/capienza/g, "capacity"],
  [/Capienza aggiornata a ([\d.]+) partecipanti\./g, "Capacity updated to $1 participants."],
  [/Raggio notifica/g, "Notification radius"],
  [/Raggio macro-area/g, "Macro-area radius"],
  [/Raggio dal capofila/g, "Leader radius"],
  [/ posti\b/g, " seats"],
  [/ dispositivi\b/g, " devices"],
  [/ partecipanti\b/g, " participants"],
  [/ tappe\b/g, " stops"],
  [/\bGEN\b/g, "JAN"],
  [/\bFEB\b/g, "FEB"],
  [/\bMAR\b/g, "MAR"],
  [/\bAPR\b/g, "APR"],
  [/\bMAG\b/g, "MAY"],
  [/\bGIU\b/g, "JUN"],
  [/\bLUG\b/g, "JUL"],
  [/\bAGO\b/g, "AUG"],
  [/\bSET\b/g, "SEP"],
  [/\bOTT\b/g, "OCT"],
  [/\bNOV\b/g, "NOV"],
  [/\bDIC\b/g, "DEC"],
  [/\bgen\b/g, "Jan"],
  [/\bfeb\b/g, "Feb"],
  [/\bmar\b/g, "Mar"],
  [/\bapr\b/g, "Apr"],
  [/\bmag\b/g, "May"],
  [/\bgiu\b/g, "Jun"],
  [/\blug\b/g, "Jul"],
  [/\bago\b/g, "Aug"],
  [/\bset\b/g, "Sep"],
  [/\bott\b/g, "Oct"],
  [/\bnov\b/g, "Nov"],
  [/\bdic\b/g, "Dec"],
];

function translateValue(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return value;
  let translated = translations[trimmed] ?? trimmed;
  for (const [pattern, replacement] of replacements) translated = translated.replace(pattern, replacement);
  return value.replace(trimmed, translated);
}

function translateTree(root: Node) {
  if (root.nodeType === Node.TEXT_NODE) {
    const text = root as Text;
    const translated = translateValue(text.data);
    if (translated !== text.data) text.data = translated;
    return;
  }
  if (!(root instanceof Element)) return;
  if (root.matches("[data-no-translate]")) return;
  for (const attribute of ["placeholder", "aria-label", "title", "alt", "value"]) {
    const value = root.getAttribute(attribute);
    if (value) {
      const translated = translateValue(value);
      if (translated !== value) root.setAttribute(attribute, translated);
    }
  }
  for (const child of root.childNodes) translateTree(child);
}

export function DashboardLanguage({ children }: { children: ReactNode }) {
  const language = useSyncExternalStore<"it" | "en">(
    () => () => {},
    () => window.localStorage.getItem("onepixel.dashboard.language") === "en" ? "en" : "it",
    () => "it",
  );

  useEffect(() => {
    document.documentElement.lang = language;
    if (language !== "en") return;
    translateTree(document.body);
    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        if (mutation.type === "characterData") translateTree(mutation.target);
        if (mutation.type === "attributes") translateTree(mutation.target);
        for (const node of mutation.addedNodes) translateTree(node);
      }
    });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ["placeholder", "aria-label", "title", "alt", "value"] });
    return () => observer.disconnect();
  }, [language]);

  function toggle() {
    const next = language === "it" ? "en" : "it";
    window.localStorage.setItem("onepixel.dashboard.language", next);
    document.cookie = `onepixel_dashboard_locale=${next}; Path=/; Max-Age=31536000; SameSite=Lax`;
    window.location.reload();
  }

  return <>
    {children}
    <button type="button" onClick={toggle} data-language-switch data-no-translate className="fixed bottom-4 right-4 z-[2000] flex h-11 items-center gap-2 rounded-full border border-white/12 bg-[#111516]/95 px-4 font-mono text-[10px] font-semibold text-[#d1e66a] shadow-2xl backdrop-blur-xl transition hover:border-[#d1e66a]/35 active:scale-[.97]" aria-label={language === "it" ? "Switch dashboard to English" : "Passa la dashboard in italiano"}><GlobeHemisphereWestIcon size={15} />{language === "it" ? "EN" : "IT"}</button>
  </>;
}
